openapi: 3.0.0
info:
  title: Supreme Cheta API
  description: Multi-vendor E-commerce Platform API
  version: 1.1.0
  contact:
    email: support@supremecheta.com

servers:
  - url: http://localhost:5001/api
    description: Development server
  - url: https://api.supremecheta.com
    description: Production server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # ---------- COMMON ----------
    ObjectId:
      type: string
      description: MongoDB ObjectId
      example: "652f1c8a2c5d3f0012ab34cd"

    # ---------- USERS / AUTH ----------
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        role:
          type: string
          enum: [customer, vendor, admin]
        profile:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
            phone:
              type: string
    
    # ---------- PRODUCTS (unchanged) ----------
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: number
        description:
          type: string
        vendorId:
          type: string
          format: uuid
        category:
          type: array
          items:
            type: string
        inventory:
          type: object
          properties:
            quantity:
              type: number
            status:
              type: string

    # ---------- CATEGORIES ----------
    Category:
      type: object
      description: Category resource returned by the API
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        parentCategory:
          type: string
          format: uuid
          nullable: true
          description: "Parent category ID (null if main category)"
        subcategories:
          type: array
          items:
            $ref: '#/components/schemas/ObjectId'
        image:
          type: string
          nullable: true
          description: Relative path stored in DB (e.g., "uploads/categories/file.png")
          readOnly: true
        imageUrl:
          type: string
          format: uri
          nullable: true
          description: Absolute URL for the frontend to render (computed by server)
          readOnly: true
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true

    CategoryCreate:
      type: object
      description: Multipart form to create a category. Send file under field name "image".
      properties:
        name:
          type: string
        description:
          type: string
        parentCategory:
          $ref: '#/components/schemas/ObjectId'
        image:
          type: string
          format: binary
          description: Image file to upload
      required: [name]

    CategoryUpdate:
      type: object
      description: Multipart form to update a category. Any field is optional; include "image" to replace the existing image.
      properties:
        name:
          type: string
        description:
          type: string
        parentCategory:
          $ref: '#/components/schemas/ObjectId'
        image:
          type: string
          format: binary
          description: New image file to upload (replaces old image)

paths:
  # ---------- AUTH ----------
  /auth/register:
    post:
      tags: [Authentication]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input

  /auth/login:
    post:
      tags: [Authentication]
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials

  # ---------- PRODUCTS ----------
  /products:
    get:
      tags: [Products]
      summary: Get all products
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
        - in: query
          name: category
          schema:
            type: string
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

    post:
      tags: [Products]
      summary: Create a new product
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not a vendor

  # ---------- CATEGORIES ----------
  /categories:
    get:
      tags: [Categories]
      summary: Get all categories
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

    post:
      tags: [Categories]
      summary: Create a new category (with optional image upload)
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CategoryCreate'
      responses:
        '201':
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not an admin

  /categories/{id}:
    get:
      tags: [Categories]
      summary: Get a category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Category details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Category not found

    put:
      tags: [Categories]
      summary: Update a category (optionally replace image)
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CategoryUpdate'
      responses:
        '200':
          description: Category updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Category not found

    delete:
      tags: [Categories]
      summary: Delete a category
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Category deleted successfully
        '404':
          description: Category not found
        '403':
          description: Forbidden - Only admins can delete categories

  /categories/{id}/subcategories:
    get:
      tags: [Categories]
      summary: Get subcategories of a category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of subcategories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '404':
          description: Category not found
